#index:
#    path: /
#    controller: App\Controller\DefaultController::index

mentions_legales:
  path: /mentions-legales.html
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
    template: static/mentions-legales.html.twig

cgv:
  path: /conditions-generales-de-vente.html
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
    template: static/cgv.html.twig

retour:
  path: /retour.html
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
    template: static/retour.html.twig

livraison:
  path: /livraison.html
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
    template: static/livraison.html.twig