<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20190625105013 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('INSERT INTO `product` (`id`, `sub_category_id`, `title`, `description`, `photo`, `price`, `slug`, `marque`, `color`, `composition`, `dimension`) VALUES
                            (127, 34, \'Cage Canto pour Oiseaux\', \'<p>Canto est une cage &agrave; oiseaux pour canaris et oiseaux exotiques, id&eacute;ale pour les phases de sevrage des oisillons ou pour des situations d&#39;incompatibilit&eacute; temporaire entre les oiseaux, gr&acirc;ce &agrave; la cloison qui s&eacute;pare l&#39;habitat en deux zones distinctes. Lorsque la s&eacute;paration est enlev&eacute;e, vous aurez une cage vraiment spacieuse qui vous permettra de garder plusieurs esp&egrave;ces d&#39;oiseaux en m&ecirc;me temps.<br />\r\n<br />\r\nCanto est facile &agrave; nettoyer et, comme toutes les cages &agrave; oiseaux Ferplast, elle dispose d&#39;un bac en plastique avec tiroirs amovibles. &Agrave; l&#39;int&eacute;rieur, vous trouverez aussi des accessoires utiles, comme des abreuvoirs, des perchoirs en caoutchouc souple qui permettront d&#39;&eacute;viter les blessures et callosit&eacute;s sur les pieds des oiseaux. Vous trouverez &eacute;galement, des mangeoires pivotantes Brava 2, que vous pourrez remplir facilement de l&#39;ext&eacute;rieur.<br />\r\n<br />\r\n<strong>La cage Canto comprend :</strong></p>\r\n\r\n<ul>\r\n	<li>4 mangeoires</li>\r\n	<li>2 distributeurs d&#39;eau</li>\r\n	<li>4 perchoirs</li>\r\n	<li>2 portes frontales</li>\r\n	<li>1 porte sur le c&ocirc;t&eacute; droit - 1 porte sur le c&ocirc;t&eacute; gauche</li>\r\n	<br />\r\n	<li>La cage Canto canaris est utilisable &eacute;galement avec un support adapt&eacute; en plastique ou en m&eacute;tal avec roues.</li>\r\n</ul>\', \'cage-canto-pour-oiseaux-6d5fdbe0ac.jpeg\', 130, \'cage-canto-pour-oiseaux\', \'Ferplast\', \'Blanc\', NULL, \'71x38x60.5 cm\'),
                            (128, 34, \'Cage Primo 60 Open Empire pour Oiseaux\', \'<p>La cage Primo 60 Open Empire est une cage pour oiseaux sp&eacute;cialement d&eacute;velopp&eacute;es pour les perruches et les canaris. Cette cage est livr&eacute; avec des bols, une fontaine, un bain d&#39;oiseaux et des perches en bois. Elle est &eacute;galement tr&egrave;s spacieuse et extra haute, avec un hauteur de 115 centim&egrave;tres lorsque le toit est ouvert. Il comporte &eacute;galement deux ports &agrave; l&#39;avant pour un acc&egrave;s facile et un toit qui peut &ecirc;tre ouvert. La cage peut &ecirc;tre enti&egrave;rement d&eacute;mont&eacute;e pour un rangement peu encombrant lorsqu&#39;elle n&#39;est pas utilis&eacute;.</p>\', \'cage-primo-60-open-empire-pour-oiseaux-fdf176596e.jpeg\', 152, \'cage-primo-60-open-empire-pour-oiseaux\', \'Savic\', \'Noir\', \'Plastique\', \'80x50x115 cm\'),
                            (129, 34, \'Cage Denver pour Perroquets\', \'<p>La cage Denver est un mod&egrave;le exclusif du fabricant allemand Montana, premier concepteur de ce type de cage, et leader mondial. C&#39;est de tr&egrave;s loin le fabricant le plus s&eacute;rieux et dont la haute qualit&eacute; est reconnue.<br />\r\n<br />\r\n<strong>Ce mod&egrave;le est adapt&eacute; aux :</strong></p>\r\n\r\n<ul>\r\n	<li>Perroquets (Gris du Gabon, Amazone, Ecletus...)</li>\r\n	<li>Cacatoes (Rosalbin, Cacatoes Alba, Cacatoes Huppe Jaune...)</li>\r\n	<li>Grandes perruches</li>\r\n	<br />\r\n	<li>La cage Denver a l&#39;&eacute;norme avantage de pouvoir se placer dans le coin d&#39;une pi&egrave;ce.<br />\r\n	<br />\r\n	<strong>Caract&eacute;ristiques de la cage Denver :</strong></li>\r\n	<li>Espacement des barreaux : 25 millim&egrave;tres</li>\r\n	<li>Epaisseur des barreux : 4 millim&egrave;tres</li>\r\n	<li>Dimensions (avec protections amovibles) : 121x121x182 centim&egrave;tres</li>\r\n	<li>la fa&ccedil;ade s&rsquo;ouvre et se transforme en une plateforme ou une aire de jeu suppl&eacute;mentaire</li>\r\n	<li>un plateau amovible pour r&eacute;cup&eacute;rer facilement les d&eacute;chets, une grille coulissante (facultative) et des protections lat&eacute;rales pour &eacute;viter les projections</li>\r\n	<li>les gamelles sont coinc&eacute;es dans des pattes en acier qui emp&ecirc;cheront votre perroquet de les retirer</li>\r\n	<li>les cages Montana ont &eacute;t&eacute; les premiers &agrave; concevoir cette poign&eacute;e et cette serrure pour &eacute;viter que votre perroquet ne puisse l&#39;ouvrir</li>\r\n	<br />\r\n	<li>La peinture, brevet d&eacute;velopp&eacute; par les cages Montana, n&#39;int&egrave;gre ni plomb ni zinc. C&#39;est un point important pour la s&eacute;curit&eacute; de votre oiseau.</li>\r\n</ul>\', \'cage-denver-pour-perroquets-edfc4b703b.jpeg\', 650, \'cage-denver-pour-perroquets\', \'Montana\', \'Noir\', NULL, \'121x121x182 cm\'),
                            (130, 34, \'Cage Hacienda Play pour Perroquets\', \'<p>Cages Montana : La derni&egrave;re g&eacute;n&eacute;ration du mod&egrave;le le plus vendu avec la nouvelle serrure de porte et le nouveau syst&egrave;me de verrouillage de la porte pour la distribution de la nourriture. Super robuste avec roues en m&eacute;tal. Le toit de l&#39;aire de jeu a maintenant deux &eacute;tages et offre ainsi encore plus de possibilit&eacute;s de jeu pour nos amis &agrave; plumes.<br />\r\n<br />\r\n<strong>Caract&eacute;ristiques de la cage Hacienda Play :</strong></p>\r\n\r\n<ul>\r\n	<li>6 mangeoire : dont 2 dans l&#39;aire de jeu</li>\r\n	<li>3 perchoirs : dont 2 sur l&#39;aire de jeu</li>\r\n	<li>2 tiroirs de d&eacute;jection</li>\r\n	<li>1 protection anti-projections</li>\r\n	<br />\r\n	<li>La peinture, brevet d&eacute;velopp&eacute; par les cages Montana, n&#39;int&egrave;gre ni plomb ni zinc. C&#39;est un point important pour la s&eacute;curit&eacute; de votre oiseau.</li>\r\n</ul>\', \'cage-hacienda-play-pour-perroquets-ddb373583e.jpeg\', 500, \'cage-hacienda-play-pour-perroquets\', \'Montana\', \'Anthracite\', NULL, \'116x95x181 cm\'),
                            (131, 34, \'Cage Regina Blanche avec Options pour Oiseaux\', \'<p>Regina est une petite cage ronde, &eacute;l&eacute;gante, pour canaris, oiseaux exotiques et autres petits oiseaux. Elle est &eacute;galement disponible en version laitonn&eacute;e et peut &ecirc;tre pos&eacute;e sur ou accroch&eacute;e &agrave;&nbsp; l&#39;un de nos supports en plastique. La base avec 2 tiroirs en plastique rendent le nettoyage quotidien facile.<br />\r\nLa cage Regina est livr&eacute;e des accessoires suivants : une balan&agrave;&sect;oire, un miroir-jouet avec une clochette, des perchoirs en plastique, un abreuvoir, une pince, un godet et 2 mangeoires pivotantes Brava 1.</p>\', \'cage-regina-blanche-avec-options-pour-oiseaux-42f64f0f6f.jpeg\', 35, \'cage-regina-blanche-avec-options-pour-oiseaux\', \'Ferplast\', \'Rose\', \'Plastique, Fer\', \'12x20x49 cm\'),
                            (132, 34, \'Cage Pagode pour Oiseaux - Blanc\', \'<p>La cage Pagode est une petite cage pour oiseaux (canaris, exotiques et autres oiseaux) sous forme de pagode, &eacute;quip&eacute;e de perchoirs, miroir, abreuvoir, pince et mangeoires.</p>\r\n\r\n<p><strong>Caract&eacute;ristiques :</strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<ul>\r\n	<li>id&eacute;al pour canaris, exotiques et autres petits oiseaux</li>\r\n	<li>forme particuli&egrave;re de toit</li>\r\n	<li>grillage en m&eacute;tal recouvert de laiton</li>\r\n</ul>\', \'cage-pagode-pour-oiseaux-blanc-9526bf3b2b.jpeg\', 65, \'cage-pagode-pour-oiseaux-blanc\', \'Ferplast\', \'Noir\', NULL, \'47x29.5x50 cm\'),
                            (133, 5, \'Cage Sonia pour Oiseaux\', \'<p>La Cage &agrave; oiseaux Sonia est sp&eacute;cialement con&ccedil;ue pour les oiseaux et les calopsites mais convient &eacute;galement aux perruches. Elle est de forme rectangulaire et est livr&eacute;e avec accessoires : perchoirs en plastique recouvert de caoutchouc pour ne pas blesser les pieds d&eacute;licats de votre oiseau. Il y a &eacute;galement trois mangeoires en plastique &agrave; l&#39;int&eacute;rieur pour garantir une quantit&eacute; suffisante de nourriture.<br />\r\n<br />\r\n<strong>Pour le nettoyage et l&#39;entretien de la cage :</strong>&nbsp;il suffit simplement de d&eacute;clipser la base et proc&eacute;der &agrave; un nettoyage normal.</p>\', \'cage-sonia-pour-oiseaux-2285713eb0.jpeg\', 109, \'cage-sonia-pour-oiseaux\', \'Ferplast\', \'Gris\', NULL, \'61.5x40x65 cm\'),
                            (134, 35, \'Verseuse Décor Oiseaux\', \'<p>La bo&icirc;te &agrave; aliments Curver conservera les croquettes et les snacks de vos animaux de compagnie. On reconna&icirc;t la bo&icirc;te par son impression sympathique. Votre animal savourera les aliments dont la fra&icirc;cheur est pr&eacute;serv&eacute;e gr&acirc;ce &agrave; la fermeture herm&eacute;tique.</p>\', \'verseuse-decor-oiseaux-691622b47b.jpeg\', 18, \'verseuse-decor-oiseaux\', \'Curver\', \'Gris\', \'Polypropylene\', \'28x11x27 cm\'),
                            (135, 35, \'Mangeoire Transparente et Design en Plastique\', \'<p>Cette mangeoire se fixe solidement &agrave; l&#39;int&eacute;rieur de la cage offrant &agrave; votre oiseau un repas dans la plus grande s&eacute;curit&eacute;. Il s&#39;accrochera sur son rebord sans crainte de perdre l&#39;&eacute;quilibre, un confort en plus dans son quotidien. Efficaces, les renforts sur les c&ocirc;t&eacute;s invitent au d&eacute;corticage sans laisser passer la moindre graine. On aimera sa transparence qui laisse entrevoir votre oiseau d&eacute;guster son savoureux repas.</p>\', \'mangeoire-transparente-et-design-en-plastique-a739dce80e.jpeg\', 8, \'mangeoire-transparente-et-design-en-plastique\', \'Ferplast\', \'Transparent\', \'Plastique\', \'9x9x9 cm\'),
                            (136, 35, \'Abreuvoir\', \'<p>Tr&egrave;s grand et pratique, cet abreuvoir pour perruches et calopsites permet &agrave;&nbsp; vos oiseaux d&#39;avoir toujours une eau fra&icirc;che et propre. Enti&egrave;rement en plastique avec un r&eacute;servoir transparent utile, il permet de v&eacute;rifier, d&#39;un simple coup d&#39;oeil, la quantit&eacute; d&#39;eau disponible. Le bec permet aux oiseaux de boire confortablement. Couleurs m&eacute;lang&eacute;es disponibles</p>\', \'abreuvoir-da002bb0ad.jpeg\', 8, \'abreuvoir\', \'Ferplast\', \'Transparent\', \'Plastique\', \'7.7x6.1x15.4 cm\'),
                            (137, 35, \'Mangeoire Perchoir Transparent\', \'<p>Compl&eacute;tez les nouvelles cages arabesque avec une gamme d&#39;accessoires relook&eacute;e !<br />\r\n<br />\r\nNouvelle gamme rajeunie pour les accessoires oiseaux.<br />\r\n<br />\r\nLignes &eacute;l&eacute;gantes et formes &eacute;pur&eacute;es.</p>\', \'mangeoire-perchoir-transparent-24a9b6922d.jpeg\', 5, \'mangeoire-perchoir-transparent\', \'Zolux\', \'Transparent\', NULL, \'7.5x8x7.5 cm\'),
                            (138, 35, \'Mangeoire Pivotante en Plastique Brava 1\', \'<p>Les mangeoires pour oiseaux de la gamme Brava Ferplast sont con&ccedil;ues pour &ecirc;tre faciles &agrave; utiliser et tr&egrave;s pratiques. Les petits mod&egrave;les, Brava 1 et Brava 2, conviennent aux petites et moyennes cages rectangulaires pour canaris, oiseaux exotiques et autres petits oiseaux. Ces mangeoires sont spacieuses et fonctionnelles et sont fabriqu&eacute;es en plastique transparent.<br />\r\n<br />\r\nElles sont faciles &agrave; nettoyer et, en m&ecirc;me temps, vous permettent de v&eacute;rifier, d&#39;un simple coup d&#39;oeil, la quantit&eacute; de nourriture que vos oiseaux ont &agrave; leur disposition. La principale caract&eacute;ristique de ces mangeoires et qu&#39;elles sont amovibles et peuvent &ecirc;tre facilement enlev&eacute;es de la cage pour &ecirc;tre nettoy&eacute;es facilement. Pour remplir les mangeoires de nourriture, il suffit de les tourner vers l&#39;ext&eacute;rieur.<br />\r\n<br />\r\n<strong>Pour le nettoyage et l&#39;entretien :</strong>&nbsp;vous pouvez les enlever de leur bo&icirc;tier sans risque. En outre, le syst&egrave;me de verrouillage s&eacute;curit&eacute; permettra &agrave; vos oiseux de ne pas d&eacute;placer la mangeoire, &eacute;vitant &eacute;galement les fuites accidentelles.</p>\', \'mangeoire-pivotante-en-plastique-brava-1-794341ca9f.jpeg\', 6, \'mangeoire-pivotante-en-plastique-brava-1\', \'Ferplast\', \'Transparent\', \'Plastique\', \'8.5x9.5x6.8 cm\'),
                            (139, 35, \'Échelle en Bois\', \'<p>Votre oiseau va adorer jouer avec cette &eacute;chelle en bois. Il pourra s&#39;amuser &agrave; parcourir l&#39;&eacute;chelle &agrave; travers ses 6 barreaux. Facile &agrave; monter, le jouet se fixe &agrave; la cage.</p>\', \'echelle-en-bois-f7fe1a4699.jpeg\', 4, \'echelle-en-bois\', \'Tyrol\', \'Boisé\', \'Bois\', \'6.8x1.7x27.8 cm\'),
                            (140, 35, \'Baignoire\', \'<p>Elle peut &ecirc;tre achet&eacute;e comme accessoires: L101 est une baignoir pour perroquets qui peut &ecirc;tre ins&eacute;r&eacute;e dans les cages oiseaux et fix&eacute;e de fa&agrave;&sect;on solide. Elle comporte une large base avec un bord sp&eacute;cial pour contenir l&#39;eau ainisi qu&#39;un perchoir pratique pour les oiseaux. En outre, cette baignoire pour oiseaux est aussi &eacute;quip&eacute;e d&#39;un couvercle en plastique transparent afin de pr&eacute;venir toutes formes d&#39;&eacute;claboussures.<br />\r\nDisponible en coloris panach&eacute;</p>\', \'baignoire-d155ccc504.jpeg\', 18, \'baignoire\', \'Ferplast\', NULL, \'Plastique\', \'15.5x23.5x24 cm\'),
                            (141, 35, \'Perchoir\', \'<p>Les perchoirs en plastique FPI 4180 et FPI 4182 sont des perchoirs simples, connus pour &ecirc;tre fix&eacute;s &agrave;&nbsp; n&#39;importe quel type de cage &agrave;&nbsp; barreaux verticales ou horizontales. Selon vos besoins et le type d&#39;oiseaux que vous poss&eacute;dez, vous pouvez choisir la petite taille, FPI 4180, adapt&eacute;e pour canaris, oiseaux exotiques et autres petits oiseaux, ou la grande taille, FPI 4182, id&eacute;ale pour perruches et calopsittes. Ils sont tr&egrave;s faciles &agrave;&nbsp; appliquer gr&agrave;&cent;ce aux attaches.</p>\', \'perchoir-0a40556904.jpeg\', 5, \'perchoir\', \'Ferplast\', \'Blanc\', \'Plastique\', \'2.4x18.4.x2.4\'),
                            (142, 35, \'Nid Exotique\', \'<p>PA 4452 est un nid en osier id&eacute;al pour canaris et petits oiseaux exotiques. Il est essentiel pour permettre &agrave;&nbsp; vos oiseaux d&#39;&eacute;lever leurs petits en toute tranquillit&eacute;. Ils peuvent &ecirc;tre fix&eacute;s &agrave;&nbsp; la cage gr&agrave;&cent;ce &agrave;&nbsp; des crochets m&eacute;talliques adapt&eacute;s.</p>\', \'nid-exotique-a75d149f36.jpeg\', 9, \'nid-exotique\', \'Ferplast\', \'Boisé\', \'Bois\', \'0x8.5x11.5 cm\'),
                            (143, 30, \'Aliments Gammarus pour Tortues d  Eau\', \'<p>Compl&eacute;ment alimentaire pour tortue d&#39;eau douce avec un apport en prot&eacute;ine et en calcium.</p>\r\n\r\n<p><strong>Le saviez-vous ?</strong></p>\r\n\r\n<p>En terrarium, le manque d&#39;UVB naturels doit &ecirc;tre compens&eacute; par un apport en Vitamine D3, permettant de construire et de fortifier la carapace et les os des Tortues. La Vitamine A, elle, prot&egrave;ge leurs muqueuses sensibles, leur peau et leurs yeux fragiles.</p>\r\n\r\n<p><strong>Utilisation :</strong>&nbsp;donner 2,5 grammes de Gammarus par tranche de 100 grammes de poids de la Tortue, en compl&eacute;ment d&#39;une alimentation compl&egrave;te et &eacute;quilibr&eacute;e.</p>\', \'aliments-gammarus-pour-tortues-deau-b637d8ceb6.jpeg\', 15, \'aliments-gammarus-pour-tortues-deau\', \'Animalis\', NULL, \'100% crustacés (gammarus) déshydratés\', NULL),
                            (144, 30, \'Fraises Déshydratées\', \'<p>Fraises lyophilis&eacute;es, &agrave; humidifier ou pas selon le besoin de l&#39;animal. Produit avec des vitamines naturelles importantes. Aliment pour tortues de terre, pogona, iguanes verts et autres reptiles herbivores et omnivores.</p>\', \'fraises-deshydratees-7d375cb082.jpeg\', 8, \'fraises-deshydratees\', \'JR Terra\', NULL, \'100% fraises séchées avec des vitamines naturelles\', \'6.5x6.5x6.4 cm\'),
                            (145, 30, \'Aliments Professional Herbivor\', \'<p>Sera Reptil Professional Herbivor est l&rsquo;aliment compl&eacute;mentaire &agrave; base de granul&eacute;s flottants de deux couleurs, fabriqu&eacute;s selon un proc&eacute;d&eacute; de co-extrusion hautement fonctionnel, pour tous les reptiles herbivores, tels que les tortues terrestres et les iguanes.</p>\r\n\r\n<p>Des prot&eacute;ines, des graisses v&eacute;g&eacute;tales, des algues, des vitamines et des min&eacute;raux ont &eacute;t&eacute; ajout&eacute;es, le tout assurant une croissance saine des os et de la carapace et une bonne r&eacute;sistance aux maladies.</p>\', \'aliments-professional-herbivor-1e9a7db573.jpeg\', 20, \'aliments-professional-herbivor\', \'Sera\', NULL, \'Amidon de maïs, farine de blé, gluten de blé, algu\', \'9.9x9.9x16.7 cm\'),
                            (146, 30, \'Os de Seiche Turtle Bone\', \'<p>L&#39;os de seiche est appr&eacute;ci&eacute; pour sa haute teneur naturelle en calcium. Il convient &agrave; toutes les tortues d&#39;eau, les tortues bo&icirc;tes et les tortues terrestres. Ce produit est vendu par lot de 2.</p>\', \'os-de-seiche-turtle-bone-b1c0a908ef.jpeg\', 5, \'os-de-seiche-turtle-bone\', \'Zoomed\', NULL, NULL, \'4x6x19 cm\'),
                            (147, 30, \'Aliment Naturel Gammarus pour Tortues d  Eau\', \'<p>Aliment compos&eacute; de petits crustac&eacute;s vivants au bord des eaux courantes (le Gammarus) puis tri&eacute;s et s&eacute;ch&eacute;s naturellement .Riche en calcium, en sels min&eacute;raux et en fibres .A utiliser en compl&eacute;ment de l&#39;aliment Tetra ReptoMin pour une alimentation saine</p>\', \'aliment-naturel-gammarus-pour-tortues-deau-02968c1bdd.jpeg\', 20, \'aliment-naturel-gammarus-pour-tortues-deau\', \'Tetra\', NULL, NULL, \'9.4x9.4x18.3 cm\'),
                            (148, 30, \'Alimentation pour Tortues Terrestres\', \'<p><strong>La formule du produit Grassland Tortoise</strong>&nbsp;propose un dosage &eacute;quilibr&eacute; en fibres et prot&eacute;ines pour garantir une croissance saine et un bon d&eacute;veloppement de la carapace. Cette nourriture est compos&eacute;e d&#39;herbes coup&eacute;es (avoine,fl&eacute;ole et luzerne) pour apporter les fibres dont vos tortues ont besoin. Elle contient &eacute;galement de petites quantit&eacute;s de fruits (papayes et mangue) pour le plus grand plaisir de vos animaux.</p>\r\n\r\n<p>Ce produit convient tout particuli&egrave;rement&nbsp;<strong>aux tortues m&eacute;diterran&eacute;ennes et de savane</strong>&nbsp;(Testudo hermanni, Testudo graeca, Geochelone sulcata, Geochelone pardalis...).</p>\', \'alimentation-pour-tortues-terrestres-5046e64c45.jpeg\', 12, \'alimentation-pour-tortues-terrestres\', \'Zoomed\', NULL, \'Protéine - matières grasses\', \'8.3x8.3x19 cm\'),
                            (149, 30, \'Boisson Gel Aqueux Beastie Drink pour Invertébrés\', \'<p>Gr&acirc;ce &agrave; la boisson Beastie Drink, les invert&eacute;br&eacute;s (tels que les crickets, sauterelles, millepattes et araign&eacute;es) pourront boire une eau propre sans aucun danger.</p>\r\n\r\n<p>Minimise le risque de noyade et la contamination bact&eacute;rienne habituellement associ&eacute;es &agrave; une source d&#39;eau ouverte.</p>\', \'boisson-gel-aqueux-beastie-drink-pour-invertebres-d0c8c72fd3.jpeg\', 7, \'boisson-gel-aqueux-beastie-drink-pour-invertebres\', \'Komodo\', NULL, NULL, \'10x8x8 cm\'),
                            (150, 30, \'Pommes Déshydratées pour Reptile\', \'<p>Pommes lyophilis&eacute;es, &agrave; humidifier ou pas selon le besoin de l&#39;animal. Produit avec des vitamines naturelles importantes. Aliment pour tortues de terre, pogona, iguanes verts et autres reptiles herbivores et omnivores.</p>\', \'pommes-deshydratees-pour-reptile-42d9c9d840.jpeg\', 8, \'pommes-deshydratees-pour-reptile\', \'JR Terra\', NULL, \'100% pommes séchées avec des vitamines naturelles \', \'6.5x6.5x6.4 cm\'),
                            (151, 30, \'Aliment Maintenance Formula pour Tortues d  Eau\', \'<p>Cette nourriture pour tortues d&#39;eau se pr&eacute;sente sous forme de granul&eacute;s et sa formule a &eacute;t&eacute; sp&eacute;cialement &eacute;labor&eacute;e pour favoriser la bonne croissance de vos tortues. La nourriture pour tortues d&#39;eau de Zoo Med est utilis&eacute;e et recommand&eacute;e par les zoos, les v&eacute;t&eacute;rinaires et les &eacute;leveurs professionels.<br />\r\nTout au long de la croissance des tortues d&#39;eau, leur r&eacute;gime change et les plantes repr&eacute;sentent une grande part de leur alimentation. Cette Formule Croissance est scientifiquement con&ccedil;ue pour r&eacute;pondre aux besoins nutritionnels de vos tortues d&#39;eau en d&eacute;veloppement dont la taille de la carapace se situe entre 5 et 15 cm. Pour les b&eacute;b&eacute;s tortues, choisissez la Formule D&eacute;veloppement de Zoo Med. Pour les tortues adultes, optez pour la Formule Maintenance de Zoo Med. La plupart des tortues d&#39;eau aiment se nourrir &agrave; la surface de l&#39;eau (comme les tortues de Floride, les tortues peintes et les tortues g&eacute;ographiques). Ces granul&eacute;s flottent, ce qui rend plus facile le rep&eacute;rage de la nourriture pour vos tortues.</p>\', \'aliment-maintenance-formula-pour-tortues-deau-55706f2dde.jpeg\', 9, \'aliment-maintenance-formula-pour-tortues-deau\', \'Zoomed\', NULL, NULL, \'7.9x7.9x19.1 cm\'),
                            (152, 31, \'Litière Coco Chips pour Reptiles\', \'<p>Liti&egrave;re v&eacute;g&eacute;tale &agrave; base de fibres de coco, tr&egrave;s absorbante, confortable et anti-odeurs.</p>\r\n\r\n<p><strong>Caract&eacute;ristiques :</strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<ul>\r\n	<li>Compostable</li>\r\n	<li>100% Naturel</li>\r\n	<li>Sans aucun additif</li>\r\n</ul>\', \'litiere-coco-chips-pour-reptiles-0283b704bb.jpeg\', 10, \'litiere-coco-chips-pour-reptiles\', \'Animalis\', NULL, \'20 L\', \'8x30x30 cm\'),
                            (153, 31, \'Conditionneur d  Eau pour Tortues Aquatiques\', \'<p>Ce conditionneur agit sur l&#39;eau du robinet pour la rendre moins agressive pour votre tortue. Il neutralise le chlore et chloramines et att&eacute;nue les effets des m&eacute;taux lourds.</p>\r\n\r\n<p>De plus, il contient de l&#39;aloe vera, un collo&iuml;de naturel qui prot&egrave;ge la peau et les muqueuses fragiles des tortues et des amphibiens.</p>\r\n\r\n<p><strong>Mode d&#39;emploi :</strong>&nbsp;&agrave; l&#39;aide du bouchon doseur, mesurer 10ml de produit pour 40L d&#39;eau de l&#39;aqua-terrarium.</p>\', \'conditionneur-deau-pour-tortues-aquatiques-2e3428e0d4.jpeg\', 6, \'conditionneur-deau-pour-tortues-aquatiques\', \'Animalis\', NULL, \'100 ml\', NULL),
                            (154, 31, \'Bloc Neutraliseur d  Eau Turtle Safe pour Aquarium\', \'<p>Instructions : Placez le bloc de calcium &agrave; diffusion lente Turtle Safe dans l&rsquo;eau de l&rsquo;aquarium pour tortues aquatique.</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Le bloc va alors se dissoudre et traiter l&rsquo;eau en neutralisant le chlore, les acides et les m&eacute;taux lourds. Il va aussi lib&eacute;rer du calcium.</p>\', \'bloc-neutraliseur-deau-turtle-safe-pour-aquarium-06690fe8c6.jpeg\', 3, \'bloc-neutraliseur-deau-turtle-safe-pour-aquarium\', \'Reptiles Planet\', NULL, NULL, \'9.5x13.5x2.5 cm\'),
                            (155, 31, \'Vermiculite Substrat naturel d  Incubation\', \'<p>- Convient particuli&egrave;rement bien comme substrat de ponte pour reptiles<br />\r\n- Isole la chaleur et absorbe l&#39;humidit&eacute;<br />\r\n- Assure une bonne teneur d&#39;humidit&eacute; dans l&#39;air<br />\r\n- Sans substances chimiques</p>\', \'vermiculite-substrat-naturel-dincubation-028f957f8d.jpeg\', 6, \'vermiculite-substrat-naturel-dincubation\', \'Trixie\', NULL, \'Substrat, 5 L\', \'37x27x5 cm\')');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs

    }
}
