<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20190625113559 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('INSERT INTO `product` (`id`, `sub_category_id`, `title`, `description`, `photo`, `price`, `slug`, `marque`, `color`, `composition`, `dimension`) VALUES                    
                            (157, 31, \'Purificateur Eau Aqua  Turtle pour Tortues\', \'<p><strong>AQUA&rsquo;TURTLE</strong>&nbsp;a &eacute;t&eacute; con&ccedil;u par PRODIBIO afin de lutter efficacement contre les mauvaises odeurs de l&rsquo;eau de aquaterrariums accueillants les tortues. Les bact&eacute;ries et le bloquant naturel d&rsquo;ammoniaque contenus dans&nbsp;<strong>AQUA&rsquo;TURTLE</strong>&nbsp;permettent de d&eacute;grader les d&eacute;jections des tortues afin d&rsquo;obtenir une eau plus saine. PRODIBIO recommande d&rsquo;utiliser une filtration dans l&rsquo;aquaterrarium et de proc&eacute;der &agrave; un changement d&rsquo;eau r&eacute;gulier.</p>\r\n\r\n<p>Les deux produits AQUA&rsquo;TURTLE BACTER et AQUA&rsquo;TURTLE ODOR, sont &agrave; utiliser en m&ecirc;me temps et &agrave; chaque changement d&rsquo;eau.</p>\r\n\r\n<p>Une ampoule traite de 0 &agrave; 60 litres. Lot de 4 ampoules.</p>\', \'purificateur-eau-aquaturtle-pour-tortues-dbb8d0315e.jpeg\', 6, \'purificateur-eau-aquaturtle-pour-tortues\', \'Prodibio\', NULL, NULL, \'9x1x16.5 cm\'),
                            (158, 31, \'Coco Husk Substrat pour Terrarium\', \'<p>Le Coco Husk est naturel &agrave; 100% et est id&eacute;al pour les terrariums de climat tropical ou semi-tropical. Il s&rsquo;agit d&rsquo;un substrat compos&eacute; de l&rsquo;enveloppe de la noix de coco d&eacute;coup&eacute;e en copeaux. La coque de noix de coco est naturellement active contre la prolif&eacute;ration des germes et moisissures. Un simple renouvellement partiel des parties souill&eacute;es permet de conserver l&rsquo;essentiel du substrat tout en conservant un maximum d&rsquo;efficacit&eacute;.</p>\r\n\r\n<p>&Agrave; l&rsquo;usage c&rsquo;est un mat&eacute;riau sain, pratique et &eacute;conomique. Ce substrat convient parfaitement aux tortues terrestres.</p>\', \'coco-husk-substrat-pour-terrarium-496e381513.jpeg\', 8, \'coco-husk-substrat-pour-terrarium\', \'Exo Terra\', NULL, \'10 L\', \'13x13x12 cm\'),
                            (159, 31, \'Litiere Snake Bedding pour Serpent Aspen\', \'<p>Liti&egrave;re pour serpents. Fournit un substrat s&ucirc;r et naturel permettant aux sepents, l&eacute;zards et petits animaux de former des tunnels et des nids comme ils le feraient dans la nature.</p>\', \'litiere-snake-bedding-pour-serpent-aspen-08ef1c727f.jpeg\', 30, \'litiere-snake-bedding-pour-serpent-aspen\', \'Zoomed\', NULL, \'26.4 L\', \'10.2x39.4x61 cm\'),
                            (160, 31, \'Substrat de Forêt Tropicale Rain Forest pour Terrarium\', \'<p>Le Rain Forest Exo Terra est un substrat fabriqu&eacute; &agrave; partir d&rsquo;&eacute;corce d&rsquo;arbre provenant de for&ecirc;t g&eacute;r&eacute;e durablement. Il contient de la sphaigne ce qui lui permet d&rsquo;augmenter le pouvoir hydrocospique et l&rsquo;humidit&eacute; de l&rsquo;air. Il favorise la mue et aide &agrave; pr&eacute;venir les infections respiratoires.</p>\r\n\r\n<p>Ce substrat est id&eacute;al pour ceux qui souhaitent installer des plantes naturelles afin de cr&eacute;er un climat tropical tr&egrave;s humide tout en offrant une bonne a&eacute;ration aux racines. Trait&eacute; &agrave; la chaleur afin de r&eacute;duire les contaminations bact&eacute;riennes.</p>\', \'substrat-de-foret-tropicale-rain-forest-pour-terrarium-c8fc87ad16.jpeg\', 31, \'substrat-de-foret-tropicale-rain-forest-pour-terrarium\', \'Exo Terra\', NULL, \'26.4 L\', \'10x40x60 cm\'),
                            (161, 32, \'Lampe Tropicale Repti Glo pour Terrarium 60cm\', \'<p>Le tube Repti Glo 5.0 Exo Terra offre un rendement UVB mod&eacute;r&eacute; &agrave; &eacute;lev&eacute; comme dans les milieux ombrag&eacute;s tels que les for&ecirc;ts pluviales et d&#39;autres milieux tropicaux.</p>\', \'lampe-tropicale-repti-glo-pour-terrarium-60cm-6898202f17.jpeg\', 17, \'lampe-tropicale-repti-glo-pour-terrarium-60cm\', \'Exo Terra\', NULL, NULL, \'3.5x64.5x3.5 cm\'),
                            (162, 32, \'Ampoule Solar Glo pour Terrarium Reptile\', \'<p>L&#39;ampoule Solar Glo Exo Terra simulant la lumi&egrave;re du soleil constitue la solution &agrave; l&#39;un des aspects les plus importants de l&#39;&eacute;levage des reptiles et des amphibiens, soit leur fournir les avantages de la lumi&egrave;re naturelle du soleil.</p>\', \'ampoule-solar-glo-pour-terrarium-reptile-4e773ecd0d.jpeg\', 37, \'ampoule-solar-glo-pour-terrarium-reptile\', \'Exo Terra\', NULL, NULL, \'18.5x14.5x14.5 cm\'),
                            (163, 32, \'Sable de Base Blanc pour Terrarium Désertique\', \'<p>Sable fin pour terrarium qui permet de reproduire un habitat d&eacute;sertique proche du naturel pour vos reptiles. Il favorise le comportement naturel de vos reptiles et poss&egrave;de une haute conductibilit&eacute; thermique pour &ecirc;tre utilis&eacute; aussi pour tapis et c&acirc;bles chauffants.<br />\r\n<br />\r\n<strong>Caract&eacute;ristiques du sable de base Trixie :</strong><br />\r\n<br />\r\n&bull; pas d&#39;adjonction de couleurs<br />\r\n&bull; id&eacute;al pour la ponte des &oelig;ufs de reptiles<br />\r\n&bull; facile &agrave; nettoyer</p>\', \'sable-de-base-blanc-pour-terrarium-desertique-92cd3fda55.jpeg\', 8, \'sable-de-base-blanc-pour-terrarium-desertique\', \'Trixie\', NULL, NULL, \'32x23xx5.5 cm\'),
                            (164, 32, \'Kit Tortue Terrestre\', \'<p>Kit complet pour tortue terrestre juv&eacute;nile de la marque&nbsp;<strong>Animalis</strong>&nbsp;en verre tout &eacute;quip&eacute;. Ce kit est parfait pour d&eacute;buter avec votre nouvelle tortue terrestre !</p>\r\n\r\n<p><strong>Caract&eacute;ristiques :</strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<ul>\r\n	<li>Spot Clamp Lamp : ampoule UV chauffante incluse</li>\r\n	<li>&Eacute;cuelle incluse</li>\r\n	<li>Terrarium pour tortue juv&eacute;nile</li>\r\n</ul>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Visuel non contractuel, d&eacute;cors et fond non inclus.</p>\', \'kit-tortue-terrestre-55880f8d1f.jpeg\', 109, \'kit-tortue-terrestre\', \'Animalis\', NULL, NULL, \'60x30x20 cm\'),
                            (165, 32, \'Mangeoire Repti Rock pour Réptiles\', \'<p>Incassable en plastique recycl&eacute;, Forme basse, surface lisse non poreuse qui ne retient pas les bact&eacute;ries.</p>\', \'mangeoire-repti-rock-pour-reptiles-3035c5a072.jpeg\', 5, \'mangeoire-repti-rock-pour-reptiles\', \'Zoomed\', NULL, NULL, NULL),
                            (166, 32, \'Ampoule Infrarouge Basking Spot\', \'<p>Cette ampoule chauffante typique &eacute;met des ondes de chaleur infrarouge. Elle comporte un r&eacute;flecteur sp&eacute;cial int&eacute;gr&eacute; permettant de diriger la chaleur dans n&#39;importe quelle direction souhait&eacute;e.</p>\', \'ampoule-infrarouge-basking-spot-a62b44e030.jpeg\', 10, \'ampoule-infrarouge-basking-spot\', \'Exo Terra\', NULL, NULL, NULL),
                            (167, 32, \'Ampoule Daylight Basking Spot\', \'<p>Ampoule &agrave; large spectre reproduisant la lumi&egrave;re du jour muni d&#39;un manchon de n&eacute;odyme. Le spectre est id&eacute;al pour la photosynth&egrave;se des plantes et les rayons UVA (ultraviolets A) contribuent au bien-&ecirc;tre physiologique des reptiles.</p>\', \'ampoule-daylight-basking-spot-8eacfa3353.jpeg\', 18, \'ampoule-daylight-basking-spot\', \'Exo Terra\', NULL, NULL, \'10x14x10 cm\'),
                            (168, 32, \'Bol pour Reptile\', \'<p>Les bols &agrave; eau Exo Terra ont un fini de rocher tr&egrave;s naturel et r&eacute;aliste sur la face ext&eacute;rieure, et une surface lisse, non granuleuse, sur la face int&eacute;rieure. Ils sont pourvus d&#39;un rev&ecirc;tement destin&eacute; &agrave; emp&ecirc;cher le d&eacute;veloppement de bact&eacute;ries nocives.</p>\', \'bol-pour-reptile-3fef894e89.jpeg\', 9, \'bol-pour-reptile\', \'Exo Terra\', NULL, \'Résine\', NULL),
                            (169, 32, \'Terrarium en Verre pour Reptile\', \'<p>Offrez une maison confortable et spacieuse &agrave; votre reptile : Exo Terra vous propose un Terrarium en Verre pour Reptile. Ce terrarium Exo Terra apportera &agrave; votre reptile des conditions similaires &agrave; celles de son lieu de vie naturel.</p>\', \'terrarium-en-verre-pour-reptile-99ca1d8818.jpeg\', 80, \'terrarium-en-verre-pour-reptile\', \'Exo Terra\', NULL, \'Verre\', \'30x30x45 cm\'),
                            (170, 27, \'Foin de Montagne\', \'<p>Cette flore tr&egrave;s riche qui compose le foin de montagne, apporte &agrave; votre petit compagnon des prot&eacute;ines &agrave; haute valeur nutritionnelle, des min&eacute;raux essentiels et des fibres v&eacute;g&eacute;tales de grande qualit&eacute;.</p>\', \'foin-de-montagne-b50c6ff1ca.jpeg\', 7, \'foin-de-montagne\', \'Animalis\', NULL, \'Trefle, fléole des près, fleurs,raygrasse, fétuque\', NULL),
                            (171, 27, \'Petit Foin de Prairie pour Rongeur\', \'<p>Moelleux et vert, le petit foin de prairie garantit le bien-&ecirc;tre des rongeurs dont il garnit avantageusement l&#39;habitat. Le petit foin de prairie constitue un environnement sain pour vos rongeurs de tous types. Adapt&eacute; &agrave; tous les &acirc;ges, il est d&#39;origine naturelle. Le petit foin de prairie est conditionn&eacute; dans un sac de 30 litres afin de vous garantir une utilisation sur la dur&eacute;e. Bien vert et moelleux, vos rongeurs ne s&#39;y tromperont pas en s&#39;y lovant pour une sieste ou en le croquant &agrave; l&#39;occasion d&#39;une petite faim.</p>\', \'petit-foin-de-prairie-pour-rongeur-2014894af4.jpeg\', 3, \'petit-foin-de-prairie-pour-rongeur\', \'Paradisio\', NULL, \'Sans additif\', NULL),
                            (172, 27, \'Foin aux Plantes Aromatiques\', \'<p>Cette flore riche, agr&eacute;ment&eacute;e de Thym et de Lavande qui compose le foin de prairie aromatique, apporte &agrave; votre petit compagnon des prot&eacute;ines &agrave; haute valeur nutritionnelle, des min&eacute;raux essentiels et des fibres v&eacute;g&eacute;tales de grande qualit&eacute;.</p>\', \'foin-aux-plantes-aromatiques-f30c2ff708.jpeg\', 7, \'foin-aux-plantes-aromatiques\', \'Animalis\', NULL, NULL, NULL),
                            (174, 27, \'Foin Premium aux Pissenlit\', \'<p>La r&eacute;colte du foin s&eacute;ch&eacute; en grange se fait au printemps, au meilleur stade de sa valeur alimentaire. L&#39;herbe est ramass&eacute;e &agrave; un taux de 45 &agrave; 70 % de mati&egrave;re s&egrave;che : le temps de s&eacute;chage au champ est donc limit&eacute;. L&#39;herbe est moins ab&icirc;m&eacute;e et moins travaill&eacute;e par les engins de fanage et les pertes de feuilles, surtout des l&eacute;gumineuses, sont r&eacute;duites. Cette m&eacute;thode de travail garantit un foin Hami Form bien &eacute;quilibr&eacute;, riche en prot&eacute;ines et app&eacute;tant. &bull; Respect de l&#39;environnement<br />\r\nHami Form a toujours prot&eacute;g&eacute; l&rsquo;environnement par la mise en place d&rsquo;une agriculture raisonn&eacute;e : l&#39;utilisation d&#39;outils l&eacute;gers, la pr&eacute;sence d&#39;un couvert v&eacute;g&eacute;tal quasi-permanent et les travaux du sol moins fr&eacute;quents.</p>\', \'foin-premium-aux-pissenlit-b6a903aa9b.jpeg\', 8, \'foin-premium-aux-pissenlit\', \'HamiForm\', NULL, NULL, \'14x25x37 cm\'),
                            (175, 27, \'Sticks à Grignoter Carotties à la Carotte pour Lapins Nains\', \'<p>Tr&egrave;s faciles &agrave; dig&eacute;rer, b&acirc;tonnets de carottes, de c&eacute;r&eacute;ales et de verdure.</p>\', \'sticks-a-grignoter-carotties-a-la-carotte-pour-lapins-nains-014119da42.jpeg\', 4, \'sticks-a-grignoter-carotties-a-la-carotte-pour-lapins-nains\', \'Vitakraft\', NULL, \'Céréales 90,6%, légumes (carottes séchées 4%)\', \'5.4x8.6x16 cm\'),
                            (176, 27, \'Friandises Kräcker aux Légumes pour Lapins Nains\', \'<p>Aux l&eacute;gumes pour lapins mains. Le plein d&#39;&eacute;nergie et de vitamines.</p>\', \'friandises-kracker-aux-legumes-pour-lapins-nains-d69ce575ea.jpeg\', 3, \'friandises-kracker-aux-legumes-pour-lapins-nains\', \'Vitakraft\', NULL, \'céréales, légumes 9,3%, sous-produits végétaux, mi\', \'3.4x8.2x18.8 cm\'),
                            (177, 27, \'Foin Premium à la Menthe\', \'<p>&bull; Aliment de qualit&eacute;<br />\r\nLa r&eacute;colte du foin s&eacute;ch&eacute; en grange se fait au printemps, au meilleur stade de sa valeur alimentaire. L&#39;herbe est ramass&eacute;e &agrave; un taux de 45 &agrave; 70 % de mati&egrave;re s&egrave;che : le temps de s&eacute;chage au champ est donc limit&eacute;. L&#39;herbe est moins ab&icirc;m&eacute;e et moins travaill&eacute;e par les engins de fanage et les pertes de feuilles, surtout des l&eacute;gumineuses, sont r&eacute;duites. Cette m&eacute;thode de travail garantit un foin Hami Form bien &eacute;quilibr&eacute;, riche en prot&eacute;ines et app&eacute;tant.<br />\r\n&bull; Respect de l&#39;environnement<br />\r\nLe foin s&eacute;ch&eacute; ne rejette ni d&eacute;chet plastique, ni jus et odeur. L&#39;allongement des rotations, l&#39;utilisation d&#39;outils l&eacute;gers, la pr&eacute;sence d&#39;un couvert v&eacute;g&eacute;tal quasi-permanent et les travaux du sol moins fr&eacute;quents contribuent &agrave; limiter les risques agronomiques.&nbsp;<br />\r\n&bull; Haute valeur nutritive&nbsp;<br />\r\nLe temps de s&eacute;chage au champ est limit&eacute; et donc moins d&eacute;pendant des conditions m&eacute;t&eacute;orologiques. Nous contr&ocirc;lons r&eacute;guli&egrave;rement l&rsquo;&eacute;volution du s&eacute;chage.</p>\', \'foin-premium-a-la-menthe-7885dec51f.jpeg\', 8, \'foin-premium-a-la-menthe\', \'HamiForm\', NULL, \'Laisser à disposition de votre animal une ration é\', \'14x25x25 cm\'),
                            (178, 27, \'Mini Snack Maïs pour Rongeur\', \'<p>Friandise 100% naturelle pour les petits rongeurs.</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<ul>\r\n	<li>R&eacute;gule la pousse dentaire</li>\r\n</ul>\', \'mini-snack-mais-pour-rongeur-b177a545e0.jpeg\', 7, \'mini-snack-mais-pour-rongeur\', \'Animalis Nature\', NULL, \'260 g\', NULL),
                            (179, 28, \'Litière en Granulés Prop  O Bois Croq  Circus\', \'<p>Cette liti&egrave;re pour rongeurs est 3 fois plus absorbante et efficace que les liti&egrave;res normales. Elle retient plus facilement les odeurs, et est optimale jusqu&#39;&agrave; 6 semaines d&#39;utilisation. Les bois proviennent de for&ecirc;ts fran&ccedil;aises et allemandes. Cette liti&egrave;re est 100% naturelle et est garantie sans pesticide, ni produit de traitement . Elle est d&eacute;poussi&eacute;r&eacute;e et permet &agrave; votre rongeur d&#39;avoir une respiration plus facile. Le nettoyage est facile, car la liti&egrave;re ne colle pas &agrave; la cage ni aux pattes de votre animal de compagnie. Ces produits sont 100% biod&eacute;gradables et l&#39;emballage fabriqu&eacute; en poly&eacute;thyl&egrave;ne est 100% recyclable. Ainsi, ce produit prend soin de la nature et de votre animal en m&ecirc;me temps. Votre rongeur et vous n&#39;allez plus pouvoir vous passer de cette liti&egrave;re naturelle.</p>\', \'litiere-en-granules-propo-bois-croqcircus-9982e74bf9.jpeg\', 9, \'litiere-en-granules-propo-bois-croqcircus\', \'Tyrol\', NULL, \'10 L\', \'27x9x45 cm\')');
        $this->addSql('INSERT INTO `product` (`id`, `sub_category_id`, `title`, `description`, `photo`, `price`, `slug`, `marque`, `color`, `composition`, `dimension`) VALUES
                            (317, 16, \'Litière Végétale Smart Pellets\', \'<p>La liti&egrave;re&nbsp;<strong>Cat&#39;s Best Smart Pellets</strong>&nbsp;est id&eacute;ale pour les chats &agrave; poils longs ! Compos&eacute;e de fibres v&eacute;g&eacute;tales sous forme de petits pellets plus lourds, celles-ci n&#39;accrochent plus aux poils des chats (sp&eacute;cialement ceux &agrave; poils longs) et retombent dans le bac &agrave; liti&egrave;re du chat. Ainsi, finie la liti&egrave;re diss&eacute;min&eacute;e partout dans la maison !<br />\r\n<br />\r\n<strong>Cat&#39;s Best Smart Pellets</strong>&nbsp;absorbe jusqu&rsquo;&agrave; 7 fois son volume en liquide et &agrave; donc une dur&eacute;e d&rsquo;utilisation de 4 &agrave; 6 semaines. Son efficacit&eacute; permet donc une utilisation optimis&eacute;e (changement de la couche de base pr&eacute;conis&eacute; toutes les 3 semaines environ suivant le type de chat). Cette liti&egrave;re dure donc plus longtemps qu&rsquo;une liti&egrave;re min&eacute;rale classique tout en &eacute;tant 100% naturelle et &eacute;cologique !<br />\r\n<br />\r\n<strong>Caract&eacute;ristiques de la liti&egrave;re Cat&#39;s Best Smart Pellets :</strong></p>\r\n\r\n<ul>\r\n <li>Ne colle pas aux poils : id&eacute;ale et adapt&eacute;e pour les chats &agrave; poils longs !</li>\r\n <li>&Eacute;conomique et efficace avec son fort pouvoir d&#39;absorption</li>\r\n <li>Pi&egrave;ge naturel &agrave; odeurs et &agrave; germes</li>\r\n  <li>Liti&egrave;re pouvant &ecirc;tre jet&eacute;e dans les toilettes</li>\r\n  <li>100% fibres v&eacute;g&eacute;tales</li>\r\n  <li>Compostable et 100% biod&eacute;gradable</li>\r\n <li>Apporte un bien &ecirc;tre au chat tout en soulageant l&#39;inconfort des ma&icirc;tres</li>\r\n  <li>Parfum naturel frais : sans ajout d&#39;additifs chimiques ni d&#39;ar&ocirc;mes</li>\r\n <li>Facile &agrave; transporter</li>\r\n  <br />\r\n  <li><strong>Conseil d&#39;utilisation :</strong>&nbsp;ne mettre seulement que les boules agglom&eacute;r&eacute;es dans les toilettes, attendre qu&#39;elles se dissolvent puis tirer la chasse d&#39;eau. Mettre le reste de liti&egrave;re (hors souillures) dans le bac &agrave; compost ou dans la poubelle. &Agrave; noter : cette liti&egrave;re n&#39;est pas comestible.</li>\r\n</ul>\', \'litiere-vegetale-smart-pellets-592537981e.jpeg\', 9.95, \'litiere-vegetale-smart-pellets\', \'Cat  s Best\', \'beige\', \'100% fibres végétales Compostable et 100% biodégra\', \'10L\'),
                            (318, 16, \'Litière Magic Clean Classic\', \'<p>Liti&egrave;re min&eacute;rale &agrave; base de gel de silice, naturellement absorbeur d&rsquo;humidit&eacute;. Neutralisation ultra rapide des odeurs et hygi&egrave;ne renforc&eacute;e gr&acirc;ce aux granul&eacute;s bleus qui limitent la croissance des bact&eacute;ries. Efficacit&eacute; et hygi&egrave;ne garanties durant 8 semaines.</p>\', \'litiere-magic-clean-classic-0d054e31f9.jpeg\', 15.9, \'litiere-magic-clean-classic\', \'Vitakraft\', \'beige\', \'gel de silice\', \'8,4L\'),
                            (319, 16, \'Bandes Stop  Griffes Autocollantes Anti - griffes\', \'<p>Ces bandes autocollantes anti-griffes, vont emp&ecirc;cher votre chat de faire ses griffes n&#39;importe o&ugrave;. Ces bandes prennent effet imm&eacute;diatement, et sont invisibles sur les surfaces. Facile &agrave; utiliser et &agrave; mettre en place. Faites &agrave; partir de mati&egrave;res inoffensives pour votre animal, et pour l&#39;environnement ; le contact des bandes repoussera votre chat, qui ne supportera pas cette mati&egrave;re.</p>\', \'bandes-stopgriffes-autocollantes-anti-griffes-b227baf663.jpeg\', 13.95, \'bandes-stopgriffes-autocollantes-anti-griffes\', \'Muzo\', \'Vert\', \'Plastique\', \'3 cm\'),
                            (321, 16, \'Litière Minérale Parfumée Chèvrefeuille\', \'<p>Cette liti&egrave;re pour chats, en sac de 8 litres, vous assurera une cohabitation parfaite avec votre f&eacute;lin. Compos&eacute;e &agrave; base d&#39;argile 100&nbsp;% naturelle et parfum&eacute;e au ch&egrave;vrefeuille, elle constitue un gage de confort pour les chats comme pour votre int&eacute;rieur, mais aussi un geste &eacute;cologique pour l&#39;environnement.</p>\', \'litiere-minerale-parfumee-chevrefeuille-15cf3e1e45.jpeg\', 3.6, \'litiere-minerale-parfumee-chevrefeuille\', \'Paradisio\', \'beige\', \'Plastique hygiénique\', \'8L\'),
                            (322, 17, \'Jouet KeekaBOO Pollie\', \'<p>Jouet pour chat avec Catnip : mettre le Catnip dans le jouet par l&#39;interm&eacute;diaire du velcro &agrave; l&#39;arri&egrave;re, bien refermer et vous avez cr&eacute;&eacute; un jouet dont votre chat ne se lassera pas ! Avec Catnip de 25ml pour le jouet.<br />\r\n<br />\r\n<strong>Avis de s&eacute;curit&eacute; : le jouet n&#39;est pas indestructible. &Agrave; utiliser sous la surveillance d&#39;un adulte. Ne convient pas aux enfants.</strong></p>\', \'jouet-keekaboo-pollie-cd0a849529.jpeg\', 6.95, \'jouet-keekaboo-pollie\', \'Europet Bernina\', \'gris\', \'Polyester\', \'14,9x13,3 cm\'),
                            (323, 17, \'Chaussette de Noël\', \'<p>Assortiment de jouets festifs se composant de plusieures types de balles et de coussinets &agrave; l&#39;herbe-aux-chats pour procurer &agrave; votre chats des heures de jeu sous le sapin. Parfait pour le d&eacute;poser au pied du sapin et faire plaisir &agrave; votre petit chat !<br />\r\n<br />\r\n<strong>Conseils d&#39;utilisation :</strong>&nbsp;Destin&eacute; exclusivement aux chats et &agrave; utiliser sous surveillance seulement. Enlever tout l&#39;emballage avant utilisation. Ne convient pas aux enfants de moins de 36 mois.</p>\', \'chaussette-de-noel-d6467f9e10.jpeg\', 5.95, \'chaussette-de-noel\', \'Armitage\', \'beige\', \'Polyester\', \'15 cm\'),
                            (324, 17, \'Canne à Pêche Papillon\', \'<p>Canne &agrave; p&ecirc;che avec papillon en son extr&eacute;mit&eacute;.<br />\r\n<br />\r\nTaille de la canne : 40cm. Des heures de jeu avec votre compagnon !<br />\r\n<br />\r\nConvient aux Chats et aux Chatons.</p>\', \'canne-a-peche-papillon-7f21a2eed3.jpeg\', 3.95, \'canne-a-peche-papillon\', \'Anka\', \'beige\', \'bois\', \'30 cm\'),
                            (325, 17, \'Chat Souris + Balle\', \'<p>Le jeu permet de renforcer les liens unissant un chat &agrave; son ma&icirc;tre. Un animal a tant &agrave; vous apporter et n&rsquo;attend en contrepartie presque rien de vous. Offrez-lui le meilleur, il le m&eacute;rite tous les jours ! Acheter des accessoires de qualit&eacute; comme ce jouet souris + balle est une preuve de consid&eacute;ration. Anka est une marque connue pour ses articles de qualit&eacute;, ainsi que le soin apport&eacute; &agrave; la fabrication.</p>\', \'chat-souris-balle-e547dec498.jpeg\', 3.95, \'chat-souris-balle\', \'Anka\', \'Noir-marron\', \'Polyester,plastique\', \'14 cm\'),
                            (326, 17, \'Souris Feutre\', \'<p>Jouet pour chat 2 souris feutre avec organe sonore inclus.<br />\r\n<br />\r\nD&egrave;s que votre chat appuiera de son poids sur la souris, elle fera un bruit sonore qui le suprendra !<br />\r\nDimensions 6 cm</p>\', \'souris-feutre-0ba690753e.jpeg\', 2.95, \'souris-feutre\', \'PetSafe\', \'Multicolore\', \'Plastique\', \'6 cm\'),
                            (327, 18, \'Lot d  Écuelles Anti - bruit Eat on Feet\', \'<p>Il est toujours de bonne humeur et vous donne de la joie tous les jours sans contrepartie&hellip; Vous aimeriez tant lui prouver aussi &agrave; quel point vous l&rsquo;aimez ! Lui commander des accessoires f&eacute;lins de qualit&eacute; comme le lot d&#39;&eacute;cuelles anti-bruit Eat on Feet pour chat - 2&times;250ml , c&rsquo;est lui prouver une fois de plus l&rsquo;amour que vous lui portez. Se d&eacute;cider pour les accessoires Trixie, c&rsquo;est choisir la qualit&eacute; : un soin tout particulier port&eacute; &agrave; toutes les &eacute;tapes de fabrication.</p>\', \'lot-decuelles-anti-bruit-eat-on-feet-f0c4cbae17.jpeg\', 7.95, \'lot-decuelles-anti-bruit-eat-on-feet\', \'Trixie\', \'Argenté\', \'Aluminium\', \'2×250 ml\'),
                            (328, 18, \'Fontaine à Eau\', \'<p>Cette fontaine &agrave; eau unique dans son genre fera le bonheur de tout le monde &agrave; la maison. Votre chat pourra s&#39;hydrater facilement avec ses deux points d&#39;eau, il aura &eacute;galement des dents saines gr&acirc;ce &agrave; la cartouche&nbsp;<strong>Dental Care</strong>&nbsp;(disponible sur notre site : de r&eacute;f&eacute;rence 822759) que vous pouvez ins&eacute;rer dans la fontaine. Vous n&#39;aurez aucun mal &agrave; la nettoyer correctement, car elle se d&eacute;monte tr&egrave;s facilement. Elle se nettoie aussi au lave-vaisselle.</p>\r\n\r\n<p>Autre point fort : avez-vous d&eacute;j&agrave; essay&eacute; de brosser les dents de votre chat ?</p>\r\n\r\n<p>Dental Care (vendu s&eacute;par&eacute;ment) est con&ccedil;u pour &ecirc;tre utilis&eacute; sans contrainte avec la fontaine &agrave; eau Cat H2O afin d&#39;apporter une hygi&egrave;ne dentaire au quotidien avec l&rsquo;eau. Le bloc de Dental Care se dissout lentement dans l&rsquo;eau et lib&egrave;re des substances qui aident &agrave; pr&eacute;venir la formation de la plaque dentaire et le d&eacute;p&ocirc;t de tartre pour des gencives plus saines et &agrave; combattre la mauvaise haleine. Contient aussi un compl&eacute;ment de calcium pour des dents plus solides</p>\r\n\r\n<p>Il est important de proposer &agrave; votre chat une fontaine &agrave; eau, cela l&#39;incite &agrave; aller boire tout au long de la journ&eacute;e afin d&#39;&eacute;viter les probl&egrave;mes urinaires.</p>\r\n\r\n<p><strong>Caract&eacute;ristiques de la fontaine &agrave; eau Cat H2O :</strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<ul>\r\n  <li>entretien des dents de votre chat au quotidien gr&acirc;ce &agrave; la cartouche Dental Care (1 cartouche est offerte)</li>\r\n <li>syst&egrave;me de filtration &agrave; pompe ultra silencieux, garanti 3 ans</li>\r\n  <li>fabriqu&eacute; en polypropyl&egrave;ne de qualit&eacute; alimentaire</li>\r\n  <li>a&eacute;rateur pour maintenir une eau parfaitement claire</li>\r\n <li>1 filtre de rechange inclu</li>\r\n <li>design sobre et moderne pour s&#39;int&eacute;grer parfaitement dans votre int&eacute;rieur</li>\r\n</ul>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Les fontaines &agrave; eau sont vivement recommand&eacute;es par les v&eacute;t&eacute;rinaires.</strong></p>\', \'fontaine-a-eau-26118b8fd1.jpeg\', 34.95, \'fontaine-a-eau\', \'Cat H2O\', \'blanc\', \'Plastique\', \'3,5L\'),
                            (329, 18, \'Gamelle Ronde Poisson\', \'<p>Un chat vous apporte tout son amour et n&rsquo;attend rien de vous. Rendez-lui la pareille ! Commander des accessoires f&eacute;lins de qualit&eacute; comme la gamelle ronde poisson de 16cm pour chat en bleu est une preuve de consid&eacute;ration. Animo Shop ne s&eacute;lectionne que les meilleures marques comme Animalis.</p>\', \'gamelle-ronde-poisson-46b2dcba96.jpeg\', 3.95, \'gamelle-ronde-poisson\', \'Animalis\', \'Bleu\', \'Plastique\', \'16 cm\'),
                            (330, 18, \'Filet de Protection\', \'<p>Filet de protection.</p>\', \'filet-de-protection-73b989d7d4.jpeg\', 15.95, \'filet-de-protection\', \'Ferplast\', \'Transparent\', \'Polyéthylène\', \'2x1,5 m\'),
                            (331, 18, \'Tubes à Croquettes Digger Senses\', \'<p>Gr&acirc;ce &agrave; leur design astucieux, les tubes &agrave; croquettes Senses Cat It 2.0 encouragent les chats &agrave; puiser de petites portions d&rsquo;aliments avec leur patte. cette activit&eacute; naturelle et amusante emp&ecirc;che les chats de se gaver.<br />\r\nIns&eacute;rez des croquettes ou des r&eacute;gals dans les diff&eacute;rents tubes ; le chat les sortira avec ses pattes !<br />\r\nLes tubes ont des extr&eacute;mit&eacute;s arrondies facilitant l&rsquo;usage et le nettoyage.&nbsp;<br />\r\nLe jouet comprend trois tubes courts et &eacute;troits ainsi que deux tubes longs et larges vous permettant de modifier les niveaux de difficult&eacute;.<br />\r\nLa surface inclin&eacute;e peut servir &agrave; ajouter des croquettes suppl&eacute;mentaires &agrave; l&rsquo;avant des tubes.</p>\', \'tubes-a-croquettes-digger-senses-fac8c902c9.jpeg\', 17.85, \'tubes-a-croquettes-digger-senses\', \'Cat It\', \'Vert-blanc\', \'Plastique\', \'54x89x128 cm\'),
                            (332, 19, \'Collier GPS Connecté Cats\', \'<p><strong>Weenect Cats 2 est un traceur GPS pour chat connect&eacute; aux smartphones des ma&icirc;tres via une application mobile disponible sur Android et iPhone.</strong></p>\r\n\r\n<p>Il est &eacute;quip&eacute; d&#39;une carte SIM incluse dans le produit qui permet un fonctionnement sans limite de distance (contrairement aux traceurs bluetooth dont la port&eacute;e est limit&eacute;e &agrave; quelques m&egrave;tres). La carte SIM est multi-r&eacute;seaux pour une couverture maximale du territoire (99%), m&ecirc;me dans les zones recul&eacute;es comme les for&ecirc;ts ou la montagne par exemple. Votre op&eacute;rateur n&#39;a aucune incidence sur le fonctionnement du service.</p>\r\n\r\n<p>Le suivi GPS se fait en temps r&eacute;el (jusqu&#39;&agrave; une position toutes les 10 secondes) et vient accompagner d&#39;autres fonctionnalit&eacute;s comme l&#39;analyse de territoire ou bien encore le dressage (pour faire revenir votre animal par simple pression d&#39;un bouton).</p>\r\n\r\n<p>Weenect fonctionne dans plus de 100 pays, sans limite de distance. Vous pouvez &ecirc;tre &agrave; Berlin et votre animal &agrave; Paris, la qualit&eacute; de service sera toujours parfaite.</p>\', \'collier-gps-connecte-cats-c02dcdf40b.jpeg\', 79.9, \'collier-gps-connecte-cats\', \'Acana\', \'blanc\', \'Plastique\', \'58x23x10mm\'),
                            (333, 19, \'Harnais Doux et Laisse\', \'<p>Harnais doux pour chats avec laisse</p>\', \'harnais-doux-et-laisse-97d4455dc2.jpeg\', 13.99, \'harnais-doux-et-laisse\', \'Anka\', \'Noir\', \'Polyester\', \'1,20 m\')');

    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs

    }
}
